language: python
dist: xenial

addons:
  postgresql: "9.6"

matrix:
  include:
   - env: TOXENV=py35-dj20-sqlite-taggit0
     python: 3.5
   - env: TOXENV=py36-dj21-sqlite-taggit0
     python: 3.6
   - env: TOXENV=py36-dj22-sqlite-taggit1
     python: 3.6
   - env: TOXENV=py36-dj22-sqlite-taggit13
     python: 3.6
   - env: TOXENV=py37-dj30-sqlite-taggit13
     python: 3.7
   - env: TOXENV=py38-dj31-sqlite-taggit13
     python: 3.8
   - env: TOXENV=py35-dj20-postgres-taggit0
     python: 3.5
   - env: TOXENV=py36-dj21-postgres-taggit0
     python: 3.6
   - env: TOXENV=py36-dj22-postgres-taggit1
     python: 3.6
   - env: TOXENV=py36-dj22-postgres-taggit13
     python: 3.6
   - env: TOXENV=py37-dj30-postgres-taggit13
     python: 3.7
   - env: TOXENV=py38-dj31-postgres-taggit13
     python: 3.8
   - env: TOXENV=py38-dj31stable-postgres-taggit13
     python: 3.8
   - env: TOXENV=py38-djmaster-postgres-taggit13
     python: 3.8
  allow_failures:
    # allow failures against Django git master and 3.1.x stable
    - env: TOXENV=py38-dj31stable-postgres-taggit13
    - env: TOXENV=py38-djmaster-postgres-taggit13

install:
  - pip install tox
  - createdb modelcluster

script:
  tox
